### ISSUE TITLE
Texas?

### ISSUE THREAD

**Issue by birdsarah** [jwrichar/COVID19-mortality#1]
Hi, saw your fabulous dashboard here: https://covid19dashboards.com/covid-19-us-case-estimation/

Can't see Texas. Perhaps I'm missing something.

The data for texas is here: https://dshs.texas.gov/news/updates.shtm#coronavirus

**Comment by birdsarah** [comment]
Just realized the source you're using. The Texas data is available on covidtracking.com

**Comment by birdsarah** [comment]
I see:

```
Dropping 4/56 states due to lack of population data: AS, GU, MP, VI
Dropping 5/52 states due to lack of tests: GA, HI, MA, PR, TX
Dropping 4/47 states due to lack of positive tests: AK, AL, ID, WV
```

Perhaps this can be added to the final dashboard. Testing numbers went up dramatically today, so hopefully, for texas at least, they will make it to the dashboard today.

**Comment by jwrichar** [comment]
Yeah, the analysis is currently pretty strict on requiring states to report both positive and negative counts.  For awhile, Texas only reported positive tests, but not negative ones (same for a handful of other states).

It does seem like a number of those states have started reporting.  However, the problem now is that there's an assumed delay in the analysis from case counts to reported mortality counts (assumes 7 days), so even though those states are reporting now it'll still take 7 days to get them into the analysis -- meaning on the **model fitting**.  But, I can deploy a fix that at least uses them during current case prediction (i.e., the step that takes the fitted model and applies it to today's case counts).

**Comment by jwrichar** [comment]
See this commit: https://github.com/jwrichar/COVID19-mortality/commit/d3a813e8653321543a98bea268b89a2a8b7e5da2

Thanks for the heads up!

**Comment by birdsarah** [comment]
In case you're interested. There is texas data for today and although it's not in API format, the number of tests performed as of last Friday was announced in the press (an scarily low 220 - https://www.texastribune.org/2020/03/13/texas-coronavirus-cases-state-emergency-greg-abbott/)

So I did a small hack and re-ran to include texas with the data added: https://github.com/birdsarah/COVID19-mortality/blob/texas-hack/State-wise%20Unreported%20COVID-19%20Cases%20in%20the%20U.S..ipynb

As another small aside, Texas doesn't report negatives, it just reports n_tested and n_positive, and I believe https://covidtracking.com does the math, so I feel ok about my methodology.

**Comment by birdsarah** [comment]
Very cool work. Also a nice way to learn some new modeling techniques.
