### ISSUE TITLE
Model based on average or max population density

### ISSUE THREAD

**Issue by birdsarah** [jwrichar/COVID19-mortality#5]
Suggestion from a colleague to make the plot (per #4) be scaled to population density. But then I was actually thinking perhaps the model could be adjusted to that instead of testing per million.

**Comment by jwrichar** [comment]
Not a bad idea.  Because we've already set up the logistic regression framework, inserting more covariates is easy peezy.  See [here](https://github.com/birdsarah/COVID19-mortality/blob/counts_per_million/source/model.py#L48) how i did it for the other model.
